services:
  api:
    image: quip-api-es:local
    container_name: quip-api-es
    network_mode: host
    env_file: .env
    volumes:
      - ./src/data:/app/src/data
    command: >
      uvicorn quip_api_es.app:app
      --host 127.0.0.1
      --port 8080
    restart: unless-stopped
