name: CI (Python)

on:
  push:
    branches: [ main, chore/**, feat/**, fix/** ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

# Evita duplicados corriendo a la vez en la misma rama
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tiny runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install "fastapi>=0.110" "uvicorn>=0.23"

      - name: Import smoke (from src)
        run: |
          python -c "import quip_api_es, fastapi, uvicorn; print('import ok')"
