name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Lint & Format
        run: |
          poetry run ruff check .
          poetry run black . --check

      - name: Type check
        run: poetry run mypy src

      - name: Run tests
        run: poetry run pytest -q
