name: CI (Python)

on:
  push:
    branches: [ main, chore/**, feat/**, fix/** ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install project
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-build-isolation .

      - name: Import smoke (quick)
        run: python -c "import quip_api_es, fastapi, uvicorn; print('import ok')"
