# .github/workflows/ci.yml
name: CI (Python)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:  # ← importante: coincide con el check exigido en branch protection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install project
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-build-isolation .

      - name: Import smoke (quick sanity)
        run: |
          python - <<'PY'
          import quip_api_es, fastapi
          print("import ok")
          PY

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build --network=host -t quip-api-es:ci .

      - name: Run container
        env:
          QUIP_API_SUBMIT_TOKEN: ci-token
        run: |
          docker run -d --name quip-api-es \
            -e QUIP_API_SUBMIT_TOKEN="$QUIP_API_SUBMIT_TOKEN" \
            -e PENDING_STORAGE=/tmp/pending.json \
            -p 127.0.0.1:8080:8000 \
            quip-api-es:ci \
            uvicorn quip_api_es.app:app --host 0.0.0.0 --port 8000

      - name: Wait for health
        run: |
          for i in $(seq 1 120); do
            if curl -fsS http://127.0.0.1:8080/health >/dev/null; then
              echo "Service healthy"; exit 0
            fi
            sleep 0.5
          done
          echo "Timeout waiting for service" >&2
          exit 1

      - name: Smoke test
        env:
          QUIP_API_SUBMIT_TOKEN: ci-token
        run: |
          set -e
          curl -fsS http://127.0.0.1:8080/health
          curl -fsS http://127.0.0.1:8080/categories
          curl -sS -X POST http://127.0.0.1:8080/submit \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${QUIP_API_SUBMIT_TOKEN}" \
            -d '{"texto":"Smoke test desde CI"}' | tee /tmp/submit.json
          python - <<'PY'
          import json,sys
          d=json.load(open("/tmp/submit.json"))
          assert d.get("status")=="pending", d
          PY

      - name: Dump logs (always)
        if: always()
        run: docker logs quip-api-es || true

      - name: Stop container (always)
        if: always()
        run: docker rm -f quip-api-es || true
