name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Poetry (stable)
        run: python -m pip install "poetry==1.8.3"

      - name: Configure Poetry
        run: |
          poetry --version
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Lint & Format
        run: |
          poetry run ruff check .
          poetry run black . --check

      - name: Type check
        run: poetry run mypy src

      - name: Run tests
        run: poetry run pytest -q
