name: CI (Python)
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project + dev tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest httpx
          pip install .

      - name: Ruff (lint)
        run: ruff check . --output-format=github

      - name: Black (check)
        run: black --check .

      - name: Pytest
        env:
          PYTHONPATH: src
          QUIP_API_SUBMIT_TOKEN: ci-token
          PENDING_DIR: ${{ runner.temp }}
          PENDING_STORAGE: ${{ runner.temp }}/pending.json
        run: |
          set -eux
          mkdir -p "$PENDING_DIR"
          echo "[]" > "$PENDING_STORAGE"
          pytest -q
